library(shiny) 
library(dplyr)
library(statebins)
library(ggplot2)
library(data.table)
  

#open up a shinyappsio account

#Add logos 

#Email Aaron about any shiny dashboard questions 

#Begin filling out paragraphs

#Work on STW v non-STW tab

ui <- fluidPage(
   #h1("Skilled Technical Workforce", align = "center", style = "color: #232D4B"),
   #h3("Data Science for the Public Good", align = "center", style = "color: #E57200"), 
   navbarPage("Skilled Technical Workforce",
       tabPanel("About",style = "margin:80px",
                
                #Trying to render an image here
                tags$img(src='nsf.jpg', height = 50, width = 50, align = "right"),
                
                
                
                h1("SDAD/DSPG", style = "color: #E57200"),
                p("The Social and Decision Analytics Division (SDAD) is one of three research divisions within the Biocomplexity Institute and Initiative at the University of Virginia. 
                  SDAD combines expertise in statistics and social and behavioral sciences to develop evidence-based research 
                  and quantitative methods to inform policy decision-making and evaluation. 
                  The researchers at SDAD span many disciplines including statistics, economics, sociology, psychology, 
                  political science, policy, health IT, public health, program evaluation, and data science. 
                  The SDAD office is located near our nation's capital in Arlington, VA. You can learn more about us at",
                  tags$a(href="https://biocomplexity.virginia.edu/social-decision-analytics.", "https://biocomplexity.virginia.edu/social-decision-analytics."), style = "color:#232D4B"),
                p("The Data Science for the Public Good (DSPG) Young Scholars program is a summer immersive program held at SDAD. Entering its seventh year, the program engages students from across the country 
                  to work together on projects that address state, federal, and local government challenges around critical social issues relevant in the world today. 
                  DSPG young scholars conduct research at the intersection of statistics, computation, and the social sciences to determine how information 
                  generated within every community can be leveraged to improve quality of life and inform public policy. ", style = "color:#232D4B"),
                h2("Skilled Techinical Workforce Project", style = "color:#E57200"),
                ),
                
       tabPanel("Profiling",style = "margin:20px",
                
                sidebarLayout(
                  sidebarPanel(
                    h3("Burning Glass Data Profile 2010-2019", align = "center"),
                    selectInput("prof_select", label = "Year", choices = c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019)),
                    hr(),
                    helpText("note: All information regarding variable descriptions was taken from the Burning Glass Data Dictionary"),
                    h3("Variables"),
                    tags$ul(
                      tags$li("id - unique ID generated by BGT "), 
                      tags$li("jobdate - date the posting was spidered "), 
                      tags$li("state - state where job is located"),
                      tags$li("soc - code of the job assigned; these are always the first 6 digits of a job's O*NET code"), 
                      tags$li("socname - name for a posting's SOC code"), 
                      tags$li("lat - latitude"),
                      tags$li("lon - longitude"), 
                      tags$li("minedu - minimum education requirement"), 
                      tags$li("maxedu - maximum education") 
                    ),
                    
                    h3("Metrics"),
                    tags$ul(
                      tags$li("Completeness: The percentage of how complete the data is"),
                      tags$li("Validity: The percentage of data elements whose attributes possess values within the range expected for a legitimate entry"),
                      tags$li("Uniqueness: number of unique valid values that have been entered for a variable")
                    )
                  ),
                  mainPanel(
                    dataTableOutput("profile"),
                    h3("Discussion"),
                    h4("[Paragraph of any trends seen in the variables profiled over the years 2010-2019]")
                  )
                )
                
                ),
       
       #end profiling tab------------------------------------------ 
       
       
       navbarMenu("Jolts vs BGT", 
        tabPanel("Total Job Estimates",
                style = "margin-left: 150px;",
                style = "margin-top: 20px;",
                style = "margin-right: 150px;",
                h3("National and Regional Comparison of Job Estimates", style = "color:#232D4B"),
                selectInput("select", "", choices = c("national", "regional"), selected = "national"),
                plotOutput("jobsByYearOrRegion"),
                h3("Paragraph that describes how JOLTS estimates job openings and how BGT collects and records job-ads: 
                   job openings versus job-ads what are the biases in the comparisons and a paragraph that summarizes the statebins changes in the 
                   23 MOC over the years 2010-2019 between and within states (we can all brainstorm on this)")
                ),
                
        
        
        
        tabPanel("Statebins",
                fluidRow(column(3,
                                h3("SOC Definitions"),
                                tableOutput("definitions"),
                                
                              ),
                         column(7,
                                h3("Percent Difference Between Jolts and BGT", style = "color:#232D4B"),
                                sliderInput("slide", "Year", min = 2010, max = 2019, value = 2014, sep = ""),
                                plotOutput("statebins", width = "700", height = "500")  
                                )),
                tableOutput("summary")
                
                )),#end navbar
                
       #end Jolts vs BGT tab-----------------
       
       
       tabPanel("BGT: STW vs Non-STW",
                sidebarLayout(
                  sidebarPanel(width = 2,
                    sliderInput("slide2", "Year", min = 2010, max = 2019, value = 2014, sep = ""),
                    selectInput("definition", "SOC Definition", choices = c("SOC11", "SOC13", "SOC15",
                      "SOC17", "SOC19", "SOC21", "SOC23", "SOC25", "SOC27", "SOC29", "SOC31", "SOC33",
                      "SOC35", "SOC37", "SOC39", "SOC41", "SOC43", "SOC45", "SOC47", "SOC49", "SOC51", "SOC53", "SOC55")),
                    textOutput("soc")
                  ),#end sidebar panel
                
                
                mainPanel(
                 plotOutput("stw", width = "700", height = "600"),
                 dataTableOutput("stwTable")
                )
                
                )
       ),#end sidebar layout
       
       #end STW vs Non-STW-------------
       tabPanel(
         "Data Sources",
         h3("Data Sources", align = "center", style = "margin-bottom: 50px"),
         style = "margin-left: 120px;",
         style = "margin-top: 30px;",
         style = "margin-right: 120px;",
         fluidRow(
           column(3, h4("Burning Glass Technologies (BGT)")),
           column(6, p(style = "font-size:15px","Burning Glass Technologies is a market analytics firm based in Boston, MA, that uses AI technologies to collect and host a massive repository of 
                       workforce and employment data. Data are collected using a web-crawling technique that uses computer programs called spiders to browse approximately 50,000+ online job boards,
                       corporate websites, and other places where job ads are posted and extract more than 70 variables per advertisement to create this repository of jobs data."))
         ),
         hr(),
         fluidRow(style = "margin-top:100px",
                  column(3, h4("Job Openings and Labor Turnover Survery (JOLTS)")),
                  column(7, p(style = "font-size:15px", "The Job Openings and Labor Turnover Survery (JOLTS) is a federal survey conducted on approximately 16,000 occupations, collecting 
                              data on factors such as total employment, job openings, hires, quits, layoffs, and other seperations. This data will be used to benchmark against the Burning Glass data."))
         ),
         hr(),
         fluidRow(style = "margin-top:100px",
                  column(3, h4("Occupational Employment Statistics (OES)")),
                  column(7, p(style= "font-size:15px", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nunc justo, fringilla quis facilisis ut, posuere ut urna. Aenean varius, massa vel pellentesque viverra, risus tortor ultricies lectus, at sollicitudin nisl lorem ac tortor. Integer luctus diam et nibh faucibus consequat. Maecenas malesuada sagittis faucibus. Etiam odio quam, lacinia quis aliquam eu, consectetur quis dolor. Aenean vitae nunc purus. 
                              Vestibulum congue mi at augue elementum cursus. Duis nec arcu euismod, bibendum mauris a, ullamcorper purus. Cras lobortis vehicula rhoncus. Quisque et lacus in lorem gravida maximus.")))
       )
     )
   )  
   



# Define server logic required to draw a histogram
server <- function(input, output) {

  #rendering profiling table
  output$profile <- renderDataTable({
    prof2010 <- "prof2010.csv"
    prof2011 <- "prof2011.csv"
    prof2012 <- "prof2012.csv"
    prof2013 <- "prof2013.csv"
    prof2014 <- "prof2014.csv"
    prof2015 <- "prof2015.csv"
    prof2016 <- "prof2016.csv"
    prof2017 <- "prof2017.csv"
    prof2018 <- "prof2018.csv"
    prof2019 <- "prof2019.csv"
    
    if(input$prof_select == 2010){
      prof <- read.csv(prof2010)
      prof
    }else if(input$prof_select == 2011){
      prof <- read.csv(prof2011)
      prof
    }else if(input$prof_select == 2012){
      prof <- read.csv(prof2012)
      prof
    }else if(input$prof_select == 2013){
      prof <- read.csv(prof2013)
      prof
    }else if(input$prof_select == 2014){
      prof <- read.csv(prof2014)
      prof
    }else if(input$prof_select == 2015){
      prof <- read.csv(prof2015)
      prof
    }else if(input$prof_select == 2016){
      prof <- read.csv(prof2016)
      prof
    }else if(input$prof_select == 2017){
      prof <- read.csv(prof2017)
      prof
    }else if(input$prof_select == 2018){
      prof <- read.csv(prof2018)
      prof
    }else{
      prof <- read.csv(prof2019)
      prof
    }
    
  })  
  
  output$jobsByYearOrRegion <- renderPlot({
    if(input$select == "national"){
      total_wide <- read.csv("jobsByYear.csv")
      ggplot(total_wide, aes(x= year, xend = year, y = bgt, yend = jolts)) + 
        geom_segment(color = "grey60") + 
        geom_point(y = total_wide$bgt, color = "#E57200", size = 3)+
        geom_point(y = total_wide$jolts, color = "#232D4B", size = 3) +
        scale_x_continuous(breaks = 2010:2019, 
                           limits =c(2010,2019)) + 
        scale_y_continuous(breaks = seq(0, 90000000, by = 10000000), 
                           labels = c( "0", paste(seq(10, 90, by = 10), "million")), 
                           limits = c(0, 90000000),
                           expand = c(0, 0))+
        theme_classic() +
        labs(y = '', 
             x = "", 
             title = "Comparison of JOLTS and BGT Job Estimates by Year",
             subtitle= "Blue dots show JOLTS job openings estimates, \nand red dots show BGT job-ads estimates.")
    }else{
      total_wide_region <- read.csv("total_wide_region.csv")
      ggplot(total_wide_region, aes(x = year, xend = year, y = bgt, yend = jolts)) + 
        geom_segment(color = "grey60") +
        #geom_text(aes(x = year+0.32, y = bgt+ ((jolts-bgt)/2), label = paste(round(per_diff, 2), "%", sep = ""))) +
        geom_point(y = total_wide_region$bgt, color = "#E57200", size = 3)+
        geom_point(y = total_wide_region$jolts, color = "#232D4B", size = 3) +
        scale_y_continuous(labels = scales::comma, breaks = seq(0, 30000000, 5000000)) +  
        scale_x_continuous(breaks = c(2010:2019)) + 
        scale_color_manual(values=c("#E57200", "#232D4B")) +
        facet_wrap(~region) + 
        theme_minimal() +
        theme(plot.title = element_text(hjust = .5, size = 20), 
              plot.subtitle = element_text(size = 12),
              axis.title.x = element_blank(), 
              legend.position = "none", 
              strip.text.x = element_text(face = "bold",size = 12)) +
        labs(title = "BGT Job Ads vs JOLTS Job Openings by Region and Year",
             y = "Number of Job Openings/Ads",
             subtitle = "Blue dots represent JOLTS Job Openings Estimates, \nand orange dots represent BGT Job Ads.") 
      
    }
  })
  
  #Rendering statebins plot
  output$statebins <- renderPlot({
    
    #renderPlot height and width
    data <- read.csv("statebinsData.csv")
    
    viz_data <- data %>% filter(year == input$slide) 
    
    statebins(viz_data, state_col = "state", value_col = "per_diff", palette = "Blues", direction = 1, round = TRUE, name = "Percent Difference") + theme_statebins() +
      labs(title = "Percent Difference Between JOLTS and BGT Estimates by State")
    
  }) 
  
  
  #SOC definitions
  output$definitions <- renderTable({
    def <- read.csv("socDefinitions.csv")
    
    def$X <- NULL
    def
  })
    
  #Summary table 
  output$summary <- renderTable({
  
  
    #email aaron about deployment after he gets back to us about data management
    #walk through the deployment of the app
    
    data <- read.csv("occupation_groups.csv")
    
    #removes the x column by setting it to NULL
    data$X <- NULL
    
    names(data)[names(data) == "state"] <- "State"
    names(data)[names(data) == "year"] <- "Year"
    names(data)[names(data) == "per_diff"] <- "Percent Difference"
    names(data)[names(data) == "X11"] <- "SOC11"
    names(data)[names(data) == "X13"] <- "SOC13"
    names(data)[names(data) == "X15"] <- "SOC15"
    names(data)[names(data) == "X17"] <- "SOC17"
    names(data)[names(data) == "X19"] <- "SOC19"
    names(data)[names(data) == "X21"] <- "SOC21"
    names(data)[names(data) == "X23"] <- "SOC23"
    names(data)[names(data) == "X25"] <- "SOC25"
    names(data)[names(data) == "X27"] <- "SOC27"
    names(data)[names(data) == "X27"] <- "SOC27"
    names(data)[names(data) == "X29"] <- "SOC29"
    names(data)[names(data) == "X31"] <- "SOC31"
    names(data)[names(data) == "X33"] <- "SOC33"
    names(data)[names(data) == "X35"] <- "SOC35"
    names(data)[names(data) == "X37"] <- "SOC37"
    names(data)[names(data) == "X39"] <- "SOC39"
    names(data)[names(data) == "X41"] <- "SOC41"
    names(data)[names(data) == "X43"] <- "SOC43"
    names(data)[names(data) == "X45"] <- "SOC45"
    names(data)[names(data) == "X47"] <- "SOC47"
    names(data)[names(data) == "X49"] <- "SOC49"
    names(data)[names(data) == "X51"] <- "SOC51"
    names(data)[names(data) == "X53"] <- "SOC53"
    names(data)[names(data) == "X55"] <- "SOC55"
    
    
    
  
    viz_data <- data %>% filter(Year == input$slide)
    
    viz_data   
    
  })
  
  #STW vs non-STW output
  output$stw <- renderPlot({
    
    data <- read.csv("stw_edu.csv")
    
    #viz_data <- data %>% filter(year == input$slide2) 
    
    #y = input$slide2
    
    
    
    #data <- final_data %>% 
      #filter(year == y) %>%
      #arrange(desc(nobach))
    
    
    
    statebins(data[data$year == input$slide2, ], state_col = "state", value_col = "nobach", palette = "Blues", direction = 1, round = TRUE, name = "Percent of Job Ads") + theme_statebins() +
      labs(title = "Percent of BGT Job Ads That Do Not Require a College Degree by State")
  })
  
  output$stwTable <- renderDataTable({
    table <- read.csv("stw_edu.csv")
    
    names(table)[names(table) == "state"] <- "State"
    names(table)[names(table) == "year"] <- "Year"
    names(table)[names(table) == "X11"] <- "SOC11"
    names(table)[names(table) == "X13"] <- "SOC13"
    names(table)[names(table) == "X15"] <- "SOC15"
    names(table)[names(table) == "X17"] <- "SOC17"
    names(table)[names(table) == "X19"] <- "SOC19"
    names(table)[names(table) == "X21"] <- "SOC21"
    names(table)[names(table) == "X23"] <- "SOC23"
    names(table)[names(table) == "X25"] <- "SOC25"
    names(table)[names(table) == "X27"] <- "SOC27"
    names(table)[names(table) == "X27"] <- "SOC27"
    names(table)[names(table) == "X29"] <- "SOC29"
    names(table)[names(table) == "X31"] <- "SOC31"
    names(table)[names(table) == "X33"] <- "SOC33"
    names(table)[names(table) == "X35"] <- "SOC35"
    names(table)[names(table) == "X37"] <- "SOC37"
    names(table)[names(table) == "X39"] <- "SOC39"
    names(table)[names(table) == "X41"] <- "SOC41"
    names(table)[names(table) == "X43"] <- "SOC43"
    names(table)[names(table) == "X45"] <- "SOC45"
    names(table)[names(table) == "X47"] <- "SOC47"
    names(table)[names(table) == "X49"] <- "SOC49"
    names(table)[names(table) == "X51"] <- "SOC51"
    names(table)[names(table) == "X53"] <- "SOC53"
    names(table)[names(table) == "X55"] <- "SOC55"
     
    
    
    viz_data <- table%>%filter(Year == input$slide2)
    viz_data
  })
  
  output$soc <- renderText({
    if(input$definition == "SOC11"){
      print("Management Occupations")
    }else if(input$definition == "SOC13"){
      print("Business and Financial Operations Occupations")
    }else if(input$definition == "SOC15"){
      print("Computer and Mathematical Occupations")
    }else if(input$definition == "SOC17"){
      print("Architecture and Engineering Occupations")
    }else if(input$definition == "SOC19"){
      print("Life, Physical, and Social Science Occupations")
    }else if(input$definition == "SOC21"){
      print("Community and Social Service Occupations")
    }else if(input$definition == "SOC23"){
      print("Legal Occupations")
    }else if(input$definition == "SOC25"){
      print("Educational Instruction and Library Occupations")
    }else if(input$definition == "SOC27"){
      print("Arts, Design, Entertainment, Sports, and Media Occupations")
    }else if(input$definition == "SOC29"){
      print("Healthcare Practitioners and Technical Occupations")
    }else if(input$definition == "SOC31"){
      print("Healthcare Support Occupations")
    }else if(input$definition == "SOC33"){
      print("Protective Service Occupations")
    }else if(input$definition == "SOC35"){
      print("Food Preperation and Serving Related Occupations")
    }else if(input$definition == "SOC37"){
      print("Building and Grounds Cleaning and Maintenance Occupations")
    }else if(input$definition == "SOC39"){
      print("Personal Care and Service Occupations")
    }else if(input$definition == "SOC41"){
      print("Sales and Related Occupations")
    }else if(input$definition == "SOC43"){
      print("Office and Administrative Support Occupations")
    }else if(input$definition == "SOC45"){
      print("Farming, Fishing, and Forestry Occupations")
    }else if(input$definition == "SOC47"){
      print("Construction and Extraction Occupations")
    }else if(input$definition == "SOC49"){
      print("Installation, Maintenance, and Repair Occupations")
    }else if(input$definition == "SOC51"){
      print("Production Occupations")
    }else if(input$definition == "SOC53"){
      print("Transportation and Material Moving Occupations")
    }else{
      print("Military Specific Occupations")
    }
  })
  
  

  
   
}

# Run the application 
shinyApp(ui = ui, server = server) 

