#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)
library(statebins)




body <- dashboardBody(
  
  # Main panel for displaying outputs ----
  mainPanel(
    tabsetPanel(type = "tabs",
                tabPanel("About"),
                tabPanel("Data Profiling",
                 selectInput("prof_select", label = "Profile", choices = c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019)),
                 tableOutput("profile"),
                 tags$ul(
                   tags$li("id - unique ID generated by BGT "), 
                   tags$li("jobdate - date the posting was spidered "), 
                   tags$li("state - state where job is located"),
                   tags$li("soc - code of the job assigned; these are always the first 6 digits of a job's O*NET code"), 
                   tags$li("socname - name for a posting's SOC code"), 
                   tags$li("lat - latitude"),
                   tags$li("lon - longitude"), 
                   tags$li("minedu - minimum education requirement"), 
                   tags$li("maxedu - maximum education")
                 )
                 ),#End Data Profiling tab
                
                tabPanel("Table")
    ),
  
  

  
)
)

ui <- dashboardPage(
   dashboardHeader(title = "DSPG20STW"),
   dashboardSidebar(),
   body = body
  
   
)


server <- function(input, output) {
  #rendering profiling table
  output$profile <- renderTable({
    prof2010 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2010.csv"
    prof2011 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2011.csv"
    prof2012 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2012.csv"
    prof2013 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2013.csv"
    prof2014 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2014.csv"
    prof2015 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2015.csv"
    prof2016 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2016.csv"
    prof2017 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2017.csv"
    prof2018 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2018.csv"
    prof2019 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2019.csv"
    
    if(input$prof_select == 2010){
      prof <- read.csv(prof2010)
      prof
    }else if(input$prof_select == 2011){
      prof <- read.csv(prof2011)
      prof
    }else if(input$prof_select == 2012){
      prof <- read.csv(prof2012)
      prof
    }else if(input$prof_select == 2013){
      prof <- read.csv(prof2013)
      prof
    }else if(input$prof_select == 2014){
      prof <- read.csv(prof2014)
      prof
    }else if(input$prof_select == 2015){
      prof <- read.csv(prof2015)
      prof
    }else if(input$prof_select == 2016){
      prof <- read.csv(prof2016)
      prof
    }else if(input$prof_select == 2017){
      prof <- read.csv(prof2017)
      prof
    }else if(input$prof_select == 2018){
      prof <- read.csv(prof2018)
      prof
    }else{
      prof <- read.csv(prof2019)
      prof
    }
    
  })
  
}

# Run the application 
shinyApp(ui = ui, server = server)

