#DSPG20STW Shiny Dashboard

library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr) 
library(statebins)
library(shinyWidgets)




body <- dashboardBody(
  # Main panel for displaying outputs ----
  mainPanel(
    tabsetPanel(type = "tabs",
                tabPanel("About",
                         h3("Skilled Technical Workforce")),
                
                tabPanel("Data Profiling",
                 selectInput("prof_select", label = "Profile", choices = c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019)),
                 tableOutput("profile"),
                 helpText("note: All information regarding variable descriptions was taken from the Burning Glass Data Dictionary"),
                 h3("Variables"),
                 tags$ul(
                   tags$li("id - unique ID generated by BGT "), 
                   tags$li("jobdate - date the posting was spidered "), 
                   tags$li("state - state where job is located"),
                   tags$li("soc - code of the job assigned; these are always the first 6 digits of a job's O*NET code"), 
                   tags$li("socname - name for a posting's SOC code"), 
                   tags$li("lat - latitude"),
                   tags$li("lon - longitude"), 
                   tags$li("minedu - minimum education requirement"), 
                   tags$li("maxedu - maximum education") 
                 ),
                 
                 h3("Metrics"),
                 tags$ul(
                   tags$li("Completeness: The percentage of how complete the data is"),
                   tags$li("Validity: The percentage of data elements whose attributes possess values within the range expected for a legitimate entry"), 
                   tags$li("Uniqueness: number of unique valid values that have been entered for a variable")
                 ),
                 em("Paragraph of any trends seen in the variables profiled over the years 2010-2019 (we can brainstorm on this)")
                 ),#End Data Profiling tab
                
                tabPanel("BGT vs Jolts",
                em("Paragraph that describes how JOLTS estimates job openings and how BGT collects and records job-ads: 
                   job openings versus job-ads what are the biases in the comparisons and a paragraph that summarizes the statebins changes in the 
                   23 MOC over the years 2010-2019 between and within states (we can all brainstorm on this)"),
                selectInput("select", "Choose", choices = c("national", "regional"), selected = "national"),
                sliderInput("slide", "Year", min = 2010, max = 2019, value = 2014, sep = ""),
                plotOutput("statebins"),
                p("Below the map, show a summary stats table with the states ordered by percent difference (smallest to largest) and across the top are the 23 major occupation groups - the cells will have the percent of BGT jobs ads classified into each group")
                )#End BGT vs Jolts panel 
    ),
  
  

  
)
)

ui <- dashboardPage(
   dashboardHeader(title = "DSPG20STW"),
   dashboardSidebar(),
   body = body,
   skin = "black"
  
   
)


server <- function(input, output) {
  #rendering profiling table
  output$profile <- renderTable({
    prof2010 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2010.csv"
    prof2011 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2011.csv"
    prof2012 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2012.csv"
    prof2013 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2013.csv"
    prof2014 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2014.csv"
    prof2015 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2015.csv"
    prof2016 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2016.csv"
    prof2017 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2017.csv"
    prof2018 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2018.csv"
    prof2019 <- "/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/profiling_tables/prof2019.csv"
    
    if(input$prof_select == 2010){
      prof <- read.csv(prof2010)
      prof
    }else if(input$prof_select == 2011){
      prof <- read.csv(prof2011)
      prof
    }else if(input$prof_select == 2012){
      prof <- read.csv(prof2012)
      prof
    }else if(input$prof_select == 2013){
      prof <- read.csv(prof2013)
      prof
    }else if(input$prof_select == 2014){
      prof <- read.csv(prof2014)
      prof
    }else if(input$prof_select == 2015){
      prof <- read.csv(prof2015)
      prof
    }else if(input$prof_select == 2016){
      prof <- read.csv(prof2016)
      prof
    }else if(input$prof_select == 2017){
      prof <- read.csv(prof2017)
      prof
    }else if(input$prof_select == 2018){
      prof <- read.csv(prof2018)
      prof
    }else{
      prof <- read.csv(prof2019)
      prof
    }
    
  }) 
  
  #rendering jolts v bgt graph
  
  
  
  #Rendering statebins plot
  output$statebins <- renderPlot({
    data <- read.csv("/sfs/qumulo/qhome/itm3f/git/dspg20STW/data/ncses_stw/dataForInteractiveDoc/statebinsData.csv")
    
    viz_data <- data %>% filter(year == input$slide)
    
    statebins(viz_data, state_col = "state", value_col = "per_diff", palette = "Blues", direction = 1, round = TRUE, name = "Percent Difference") + theme_statebins() +
    labs(title = "Percent Difference Between JOLTS and BGT Estimates by State")
    
    
    
    },bg = "transparent")
  
  
  
  
}

# Run the application 
shinyApp(ui = ui, server = server)

